### ISSUE TITLE
翻譯 library/archiving.po

### ISSUE THREAD

**Issue by Kuo-TingKai** [python/python-docs-zh-tw#390]
這是我第一次參與開源翻譯計畫，先試翻看看這一小段沒翻到的部分，來瞭解這整個提交的流程。
![image](https://user-images.githubusercontent.com/13663890/215257058-23095550-a43c-4f2b-8ded-92a4e502bc83.png)

**Comment by mattwang44** [comment]
@Kuo-TingKai 要麻煩你[發出 PR](https://gitbook.tw/chapters/github/pull-request) 歐，目前翻譯計畫的習慣是發 PR 後才會開始 review 翻譯內容，感謝！

**Comment by Kuo-TingKai** [comment]
但我在編輯完之後執行`make all`的時候遇到錯誤:
```bash=
(base) kai@DESKTOP-8DBT08O:/mnt/c/Users/GUO/Desktop/Ting-Kai_Kuo_Projects/python-docs-zh-tw$ make all
mkdir -p ~/.venvs/python-docs-i18n/
/home/kai/miniconda3/bin/python3 -m venv ~/.venvs/python-docs-i18n/
. ~/.venvs/python-docs-i18n//bin/activate; python3 -m pip install sphinx python-docs-theme
Collecting sphinx
  Downloading sphinx-6.1.3-py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 4.4 MB/s eta 0:00:00
Collecting python-docs-theme
  Downloading python_docs_theme-2022.1-py2.py3-none-any.whl (15 kB)
Collecting sphinxcontrib-qthelp
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 KB 2.9 MB/s eta 0:00:00
Collecting snowballstemmer>=2.0
  Downloading snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 KB 4.8 MB/s eta 0:00:00
Collecting requests>=2.25.0
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 4.1 MB/s eta 0:00:00
Collecting packaging>=21.0
  Downloading packaging-23.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 KB 2.5 MB/s eta 0:00:00
Collecting importlib-metadata>=4.8
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/26/a7/9da7d5b23fc98ab3d424ac2c65613d63c1f401efb84ad50f2fa27b2caab4/importlib_metadata-6.0.0-py3-none-any.whl
  Downloading importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/sphinxcontrib-devhelp/
Collecting sphinxcontrib-devhelp
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.7/84.7 KB 733.8 kB/s eta 0:00:00
Collecting babel>=2.9
  Downloading Babel-2.11.0-py3-none-any.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 6.2 MB/s eta 0:00:00
Collecting alabaster<0.8,>=0.7
  Downloading alabaster-0.7.13-py3-none-any.whl (13 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.0
  Downloading sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.5/100.5 KB 5.7 MB/s eta 0:00:00
Collecting imagesize>=1.3
  Downloading imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Collecting Jinja2>=3.0
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting sphinxcontrib-applehelp
  Downloading sphinxcontrib_applehelp-1.0.4-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/120.6 KB ? eta -:--:--
ERROR: Exception:
Traceback (most recent call last):
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/home/kai/miniconda3/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/home/kai/miniconda3/lib/python3.9/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/home/kai/miniconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/kai/miniconda3/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/kai/miniconda3/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
    super().__init__(
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 214, in unpack_url
    file = get_http_url(
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/network/download.py", line 146, in __call__
    for chunk in chunks:
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py", line 304, in _rich_progress_bar
    for chunk in iterable:
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/kai/miniconda3/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/kai/.venvs/python-docs-i18n/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the '/home/kai/.venvs/python-docs-i18n/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by mattwang44** [comment]
- 這個訊息代表 pip install 的時候連線失敗，要確認網路連線正常
- 如果還有其他錯誤的話可以嘗試使用 `VERSION=3.11 make all`

**Comment by Kuo-TingKai** [comment]
@mattwang44  感謝你 `VERSION=3.11 make all` 對我有用(但我不太清楚為甚麼?)
我剛剛發PR了，麻煩review了，謝謝!

**Comment by mattwang44** [comment]
有留 review comment 了，再麻煩你幫忙修正，感謝！

Makefile 目前寫法是會需要知道是在處理哪一個版本 (e.g. `3.11`)，預設會使用當前 git branch 名稱，但 local 上不一定會剛好是版本名稱 (e.g. `ref/head/3.11`)，所以可以另外給定 VERSION 參數。（應該要寫在 readme 但還沒有😓）
https://github.com/python/python-docs-zh-tw/blob/93e38a65e64f791739e82ed15b025d6ebeaf0ed8/Makefile#L46

btw 如果對翻譯計畫有興趣的話，最近有個線下活動，歡迎參加！
https://sciwork.kktix.cc/events/scisprint-202202-taipei

**Comment by mattwang44** [comment]
@Kuo-TingKai 目前你開的兩個 PR 還會繼續修嗎？
